### ISSUE TITLE
ADD documentation

### ISSUE THREAD

**Issue by emquardokus** [maddy3940/ASCTB-Azimuth-Comparison-22#1]
@maddy3940 
- [x] Please add documentation that describes the output table tabs and how they were derived. This will facilitate ACTIONABLE items for the ASCT+B authors to update their tables, but I need to be able to read these tables and fully understand HOW you've determined the categories and where there are issues that need to either be author driven or possibly CL ontology editors/curators group driven. This would be very valuable. 

- [x] ASCTB_missing CTs how is this determined?
- [x] AZ_ASCT-CTs perfect matches how is this determined?
- [x] AZ-incorrect CTs---what does it mean "incorrect" in this case?
- [x] ASCTB-Incorrect CTs--what does this mean "incorrect" in this case?
- [x] Az_match_tree_corsswalk--link to crosswalk you are using
- [x] Asctb_match_tree_corsswalk -link to crosswalk you are using
- [x] Asctb_cts_mismatch_final--describe how this is  derived
- [x] Az_cts_mismatch_final---describe how this is  derived

- [x] Please add documentation on how the comparison logic is set up---what steps are taken to do the Azimuth to ASCT+B comparison.

- [x] Based on discussion in standup meeting "LABEL" is not being used the same as it is in the ASCT+B reporter or ASCT+B tables.  "LABEL" means RDFS:LABEL directly from the ontology.  
In the ASCT+B tabls 3 main columns describe AS or CT.  AS/1 = author preferred name, AS/1/LABEL = RDFS:LABEL directly from the ontology, AS/1/ID is the Uberon or FMA ID from ontology.   Same is true for CTs. CT/1 = author preferred name ,CT/1/LABEL is RDFS:LABEL directly from the ontology, CT/1/ID is the cell ontology ID for the cell type.

- [x] please tag me when you have documentation

**Comment by maddy3940** [comment]
@emquardokus  Kindly take a look and let me know if you have any questions
